Fix(dialog, popover) restore focus when manually setting `open` to `false`
melt-ui/melt-ui pull request #1110
Opened 2024-03-20 12:35 UTC by anatolzak

closes https://github.com/melt-ui/melt-ui/issues/1109

We now restore focus to the trigger (or using the `closeFocus` prop) in an `effect` that runs when `open` is `false`. In order to not focus the trigger on initial mount when `open` is `false`, I added a parameter `skipFirstRun` to the `effect` function that optionally skips the first run of the effect.

I also added regression tests for the dialog and popover. 

Also, in the menu builder, we are already doing what I implemented with the dialog and popover, which removes the need in the menu builder to manually focus the trigger in multiple places. And I cleaned up the effect in the menu component. 

### Dialog Before
https://github.com/melt-ui/melt-ui/assets/53095479/584dd6ad-bd39-4901-9ff1-2a0e987f1a2e

### Dialog After 
https://github.com/melt-ui/melt-ui/assets/53095479/ac7ac1d1-f02e-4b2a-8f48-040438149a43

### Popover Before

https://github.com/melt-ui/melt-ui/assets/53095479/89b2dc56-e1a8-47e3-9ce3-d4c42fbe41c3

### Popover After

https://github.com/melt-ui/melt-ui/assets/53095479/fa3943a1-35d1-417b-afe9-cb4f5650b69d

2024-03-21 23:27 UTC, huntabyte requested changes
Minor thing! Thanks man!

2024-03-21 23:27 UTC, huntabyte commented on src/lib/internal/helpers/store/effect.ts
> +	skipFirstRun?: boolean
Let's make this an object. @TGlide and I have spoke in the past about some other options we want to add to effects and by making it an object now it'll ease the addition of those.

```ts
type EffectOptions = {
  skipFirstRun?: boolean;
}
```

2024-03-23 14:43 UTC, anatolzak commented
@huntabyte I added an options parameter to `effect` as you requested!

2024-03-28 17:07 UTC, huntabyte approved these changes
Thank you!

2024-03-28 17:12 UTC, merged