docs: add code ignore to popover
melt-ui/melt-ui pull request #65
Opened 2023-06-19 04:17 UTC by huntabyte

Closes: #61

2023-06-19 08:24 UTC, geerew requested changes
The +page.svelte needs updated to use this 

```
	import code from './code.ignore-svelte?raw';
	...
	<Docs.CodeBlock {code} />
```

2023-06-19 17:00 UTC, huntabyte commented
Thanks for catching that! Done ✅

2023-06-20 10:32 UTC, TGlide approved these changes

2023-06-20 10:32 UTC, TGlide commented
LGTM 🎉

2023-06-20 10:33 UTC, merged