fix [object Object] ids on trigger and menu
melt-ui/melt-ui pull request #704
Opened 2023-11-07 19:57 UTC by diaasaur

fixes: #703 

noticed this error in browser console and it looks like an issue of value mismatch for ids (trigger + menu)
<img width="558" alt="Screenshot 2023-11-08 at 1 24 48 AM" src="https://github.com/melt-ui/melt-ui/assets/111369805/0bdd09c5-1a41-4fe7-9a57-76d47ba5a47c">

2023-11-07 21:06 UTC, TGlide requested changes
Thank you! Just one thing that needs to be fixed.

2023-11-07 21:06 UTC, TGlide commented on src/lib/builders/context-menu/create.ts
> +				id: get(ids.menu),
These should be reactive, meaning you should reference ids.menu in `stores`, then use it in `returned`.

2023-11-08 05:07 UTC, huntabyte commented
Just now seeing this but I already took care of this as well as the submenus and some other issues + tests in #707

2023-11-08 05:20 UTC, diaasaur commented
> Just now saw this but I already took care of this as well as the submenus and some other issues (like the screenshot of the DOM Exception) + tests in #707

no worries! I will close mine since your PR seems to take care of tests as well :D

2023-11-08 05:20 UTC, closed without merging