Add Separator component
melt-ui/melt-ui pull request #76
Opened 2023-06-21 13:23 UTC by kaevupoiss

I have tried to implement the separator component. It doesn't seem like I have to return anything else from the `createSeparator()` builder.

2023-06-21 14:20 UTC, TGlide requested changes
Thank you for the PR! Just some small changes needed 😄

2023-06-21 14:20 UTC, TGlide commented on src/lib/builders/separator/index.ts
> +    const decorative = writable(args.decorative ?? 'false');
These should be returned so they can be modified after creation

2023-06-21 14:20 UTC, TGlide commented on src/routes/docs/builders/separator/preview.svelte
> +	import { createSeparator } from '@melt-ui/svelte/builders/separator';
Should be $lib. Also, don't forget to export it from '$lib/builders/index.ts' as well

2023-06-26 18:43 UTC, huntabyte commented
Closing this in favor of #88 - thank you!

2023-06-26 18:43 UTC, closed without merging